#!/usr/bin/env bash

branch=$(pushd /etc/ConsolePi >/dev/null 2>&1 && git rev-parse --abbrev-ref HEAD && popd >/dev/null || echo "master")
[ ! "$branch" == "master" ] && echo -e "Script updating ${branch} branch.\n  You are on a development branch."
if [ ! -z "$@" ] && [ "$@" =~ '-dev' ]; then
    echo "Local Pull"
    sftp pi@consolepi-dev:/etc/ConsolePi/installer/install.sh /tmp/ConsolePi && sudo bash /tmp/ConsolePi "$@" && rm /tmp/ConsolePi
else
    wget -q https://raw.githubusercontent.com/Pack3tL0ss/ConsolePi/$branch/installer/install.sh -O /tmp/ConsolePi && sudo bash /tmp/ConsolePi && rm /tmp/ConsolePi
fi
