#!/usr/bin/env bash

# Initiates test of ConsolePi automated actions based on IP changes
#   IF No args: provided it will initiate a test, and use your configured local_domain
#               to skip openvpn if enabled.
#   Optional first Arg: [static|<some new domain>].  The keyword static, will initiate a test
#                       on the fallback to static flow used to enable dhcp server on eth interface
#                       any other string will be used as the new domain, which will trigger openvpn
#                       test
#
# . /etc/ConsolePi/ConsolePi.conf
push_response_log="/var/log/ConsolePi/push_response.log"

echo -e "\n         ConsolePi dhcpcd Exit Hook Test (test automations triggered by DHCP events)"
# ! $push && echo "!!! PushBullet Notifications are not enabled in the config !!!"
echo -e "\nSending test data to simulate dhcpcd hook\n"
sudo /etc/ConsolePi/src/dhcpcd.exit-hook test "$@" ||
    echo -e "Script returned Error Code ("$?")  Check Logs"
echo -e "\nTest Complete, if PB is enabled in the config you Should have received a msg."
echo -e "The script sends PB msg to a background process and does not evaluate the result."
echo -e "If you did not get a message check $push_response_log for response from PB api.\n"
echo -e "The Notification will display a random IP in the Subject used to trigger"
echo -e "the push, the body of the msg will still reflect your real IP\n"