#!/usr/bin/env bash

pushd /etc/ConsolePi >/dev/null
sudo git pull
popd >/dev/null
sudo cp /etc/ConsolePi/src/PyConsolePi/* /etc/ConsolePi/venv/lib/python3*/site-packages/consolepi/

if [[ "$1" == "--pip" ]] ; then
    py3ver=$(python3 -V | cut -d. -f2)
    [ $py3ver -ge 6 ] && req_file="/etc/ConsolePi/installer/requirements.txt" ||
                         req_file="/etc/ConsolePi/installer/requirements-legacy.txt"

    sudo /etc/ConsolePi/venv/bin/python3 -m pip install --upgrade pip 1>/tmp/cpi_pip.log 2>&1 &&
    sudo /etc/ConsolePi/venv/bin/python3 -m pip install --upgrade -r ${req_file} 1>/tmp/cpi_pip.log &&
    rm /tmp/cpi_pip.log || ( echo "pip upgrade retuned errors displaying log (/tmp/cpi_pip.log)" &&
        less /tmp/cpi_pip.log | +G )
fi