#!/etc/ConsolePi/venv/bin/python3

import json
import sys
from consolepi.common import ConsolePi_data
from consolepi.relay import Relays

config = ConsolePi_data(do_print=False)

hostname = config.hostname
adapters = config.get_local()
interfaces = config.get_if_ips()
relays = Relays().relay_data
remotes = config.get_local_cloud_file()
details = {hostname: {'adapters': adapters, 'interfaces': interfaces, 'user': 'pi'}, 'relays': relays, 'remotes': remotes}
        
if len(sys.argv) > 1:
    if sys.argv[1] == 'adapters':
        print(json.dumps(adapters, indent=4, sort_keys=True))
    elif sys.argv[1] == 'interfaces':
        print(json.dumps(interfaces, indent=4, sort_keys=True))
    elif sys.argv[1] == 'relays':
        print(json.dumps(relays, indent=4, sort_keys=True))
    elif sys.argv[1] == 'remotes':
        print(json.dumps(remotes, indent=4, sort_keys=True))
    else:
        try:
            print(json.dumps(details[sys.argv[1]], indent=4, sort_keys=True))
        except KeyError:
            print('!!!  {} Not Found printing entire data set   !!!'.format(sys.argv[1]))
            print(json.dumps(details, indent=4, sort_keys=True))        
else:
    print(json.dumps(details, indent=4, sort_keys=True))
