#!/usr/bin/env bash
echo "Launching ConsolePi Serial Console Menu"
if [ ! -z $1 ] && [ "$1" = 'sh' ]; then 
    sudo /etc/ConsolePi/src/consolepi-menu.sh
else
    sudo /etc/ConsolePi/src/consolepi-menu.py "${@}"
fi
