#!/usr/bin/env bash

. /etc/ConsolePi/ConsolePi.conf

echo -e "\n         ConsolePi PushBullet Test"
! $push && echo "!!! PushBullet Notifications are not enabled in the config !!!" 
echo -e "Sending test data to simulate new DHCP address\n"
sudo /etc/ConsolePi/src/dhcpcd.exit-hook test "$@"
echo "Test Complete - You Should have a PushBullet Message"
echo -e "The Notification will display a random IP in the Subject (used to trick the process and invoke the test\n"
