%YAML 1.2
# This file should not be modified.  Static variables/paths used throughout ConsolePi
# Versioning = YYYY.Major.Patch/Minor
---
CONSOLEPI_VER: 2024-3.2
INSTALLER_VER: 82
CFG_FILE_VER: 11
CONFIG_FILE_YAML: /etc/ConsolePi/ConsolePi.yaml
CONFIG_FILE: /etc/ConsolePi/ConsolePi.conf # For backward compat, use yaml config going forward
POWER_FILE: /etc/ConsolePi/power.json # For backward compat, use yaml config going forward
REM_HOSTS_FILE: /etc/ConsolePi/hosts.json # For backward compat, use yaml config going forward
LOCAL_CLOUD_FILE: /etc/ConsolePi/cloud.json
CLOUD_CREDS_FILE: /etc/ConsolePi/cloud/gdrive/.credentials/credentials.json
LOG_FILE: /var/log/ConsolePi/consolepi.log
RULES_FILE: /etc/udev/rules.d/10-ConsolePi.rules
SER2NET_FILE: /etc/ser2net.conf # To Be Removed.  ser2net cfg will be determined by program (to support 4.x yaml)
REM_LAUNCH: /etc/ConsolePi/src/remote_launcher.py
VALID_BAUD: ['300', '1200', '2400', '4800', '9600', '19200', '38400', '57600', '115200']  # TODO Not sure if this is used anymore
ZTP_DIR: /etc/ConsolePi/ztp
ZTP_CLI_FILE: /etc/ConsolePi/ztp/.ztpcli
ZTP_CLI_DEFAULT_TIMEOUT: 20
ZTP_CLI_LOGIN_MAX_WAIT: 60  # post ztp cli commands will be attempted right after cfg is sent and retry every 10 secs until this limit is reached
PARSER_DIR: /etc/ConsolePi/ztp/custom-parsers
FALLBACK_USER: consolepi # if rem_user is missing from config, or for a remote...
